package com.forgeboard.document.application;
import java.time.Clock; import java.util.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.forgeboard.client.ClientDirectory; import com.forgeboard.document.domain.DocumentRequest; import com.forgeboard.document.persistence.DocumentRequestRepository; import com.forgeboard.identity.*;
@Service public class DocumentRequestService {
    private final DocumentRequestRepository requests; private final ClientDirectory clients; private final ActivityRecorder activity; private final Clock clock;
    public DocumentRequestService(DocumentRequestRepository requests, ClientDirectory clients, ActivityRecorder activity, Clock clock){this.requests=requests;this.clients=clients;this.activity=activity;this.clock=clock;}
    @Transactional(readOnly=true) public List<DocumentRequestView> list(SelectedTenant tenant){return requests.findAllByFirmIdOrderByDueDateAsc(tenant.firmId()).stream().map(this::view).toList();}
    @Transactional public DocumentRequestView create(SelectedTenant tenant, DocumentRequestInput input){write(tenant); if(!clients.exists(tenant.firmId(),input.clientId())) throw new NoSuchElementException("Client was not found in the selected firm"); var request=requests.save(new DocumentRequest(UUID.randomUUID(),tenant.firmId(),input.clientId(),input.label().strip(),blankToNull(input.externalReference()),input.dueDate(),clock.instant())); activity.recordRestUserAction(tenant.firmId(),tenant.userId(),"document-request.created","document-request",request.id(),Map.of("label",request.label())); return view(request);}
    @Transactional public DocumentRequestView receive(SelectedTenant tenant, UUID id){write(tenant); var request=requests.findByIdAndFirmId(id,tenant.firmId()).orElseThrow(()->new NoSuchElementException("Document request was not found in the selected firm")); request.receive(clock.instant()); activity.recordRestUserAction(tenant.firmId(),tenant.userId(),"document-request.received","document-request",request.id(),Map.of("label",request.label())); return view(request);}
    private DocumentRequestView view(DocumentRequest r){return new DocumentRequestView(r.id(),r.clientId(),r.label(),r.externalReference(),r.dueDate(),r.status(),r.receivedAt(),r.version());} private String blankToNull(String v){return v==null||v.isBlank()?null:v.strip();} private void write(SelectedTenant t){if(!t.canWrite())throw new AccessDeniedException("Read-only members cannot change document requests");}
}
