export const migrationParityMatrix = String.raw`| Journey ID | Legacy behavior | Next behavior/route | Roles | Tenant/deep-link evidence | Test | Status | Replacement reason |
| --- | --- | --- | --- | --- | --- | --- | --- |
| access-onboarding | Browser session sign-in and firm onboarding | Public access page and /firms/[firmSlug] | Public, owner | Firm direct routes restore an authorized firm context | apps/web/e2e/sign-in-and-clients.spec.ts :: persists the German language choice through Auth.js and direct firm routes | parity | |
| language-selection | English/German preference on the legacy global shell | Public access and every migrated Next firm route | Public, authenticated roles | Cookie-backed German preference survives Auth.js sign-in, a firm deep link, reload, and a workflow task document action | apps/web/e2e/sign-in-and-clients.spec.ts :: persists the German language choice through Auth.js and direct firm routes | parity | |
| workflow-task-create-link-unlink | Board creation, movement, and document request operations | /firms/[firmSlug]/workflow/[workflowSlug] and /tasks/[taskReference] | Owner, administrator, manager, read-only | Canonical workflow reload; read-only and other-firm denials | apps/web/e2e/workflow-routes.spec.ts :: uses shareable workflow routes, task workspace, moves, and saved views | parity | |
| my-work | Assigned work and task navigation | /firms/[firmSlug]/my-work | Employee, manager, owner | Direct task link retains firm context | apps/web/e2e/sign-in-and-clients.spec.ts :: opens assigned work from My work and preserves the direct task link | parity | |
| clients | Create and maintain firm clients | /firms/[firmSlug]/clients | Owner, administrator, manager, read-only | Direct firm route persists client work | apps/web/e2e/sign-in-and-clients.spec.ts :: persists the German language choice through Auth.js and direct firm routes | parity | |
| engagements-document-requests | Engagement setup and metadata-only document requests | /firms/[firmSlug]/engagements | Owner, administrator, manager, read-only | Owner browser operating loop and role-restricted controls | apps/web/e2e/operational-routes.spec.ts :: runs an owner engagement and document-request operating loop through the browser | parity | |
| employees | Provision and view firm employees | /firms/[firmSlug]/employees | Owner, administrator, read-only | Browser provisioned read-only employee retains restricted access | apps/web/e2e/operational-routes.spec.ts :: provisions a read-only employee through the browser | parity | |
| audit | Firm activity trail and filters | /firms/[firmSlug]/audit-trail | Owner, manager | Direct-route filters stay firm scoped | apps/web/test/unit/features/audit/audit-trail.test.tsx :: hydrates direct-route filters and moves to the backend cursor page | parity | |
| protected-direct-routes | Protected views rely on Spring session access | Firm-routed protected Next pages | Authorized memberships | Inaccessible firm slugs render Next not-found boundary | apps/web/test/unit/routing/firm-layout.test.tsx :: uses the Next not-found boundary for an inaccessible firm slug | approved replacement | Auth.js validates route access before the BFF; Spring remains final authority. |
| tenant-negative-paths | Cross-firm resources are hidden | BFF and public routes preserve tenant-not-found behavior | All authenticated roles | Forged other-firm workflow request returns 404 | apps/web/e2e/workflow-routes.spec.ts :: does not expose another firm workflow through the browser BFF | parity | |
| canonical-urls-route-state | Legacy local view state and UUID route compatibility | Public workflow slugs, task references, and normalized URL state | Authorized workflow users | Query filters and task panel URLs preserve canonical public route state | apps/web/test/unit/features/workflow/workflow-route-state.test.ts :: opens and closes task panels without losing filters | approved replacement | Public slugs and task references replace internal UUID URLs while retaining compatibility redirects. |
| css-modules | Global Vite stylesheet | Component-scoped CSS Modules in routed Next UI | All users | Workflow board component behavior exercises the CSS Module-backed route | apps/web/test/unit/features/workflow/workflow-board.test.tsx :: creates a work item inline in its selected stage | approved replacement | CSS Modules replace the global stylesheet to prevent cross-route style coupling. |`
