export const LANGUAGE_COOKIE = 'forgeboard.language'

export const languages = ['en', 'de'] as const
export type Language = (typeof languages)[number]

const englishMessages = {
  // Access
  'access.introduction': 'ForgeBoard introduction',
  'access.eyebrow': 'The client-work operating system',
  'access.title': 'Clarity for every client engagement.',
  'access.description': 'ForgeBoard gives accounting teams one calm, accountable place to run deadlines, handoffs, and recurring work.',
  'access.oneView': 'One view',
  'access.oneViewDetail': 'of every active engagement',
  'access.clearOwnership': 'Clear ownership',
  'access.clearOwnershipDetail': 'from preparation to review',
  'access.auditReady': 'Audit ready',
  'access.auditReadyDetail': 'with every change recorded',
  'access.secureFirmAccess': 'Secure firm access',
  'access.welcomeBack': 'Welcome back',
  'access.buildWorkspace': 'Build your workspace',
  'access.signInDescription': 'Pick up where your team left off.',
  'access.onboardingDescription': 'Create the first owner account for your firm.',
  'access.accountAccess': 'Account access',
  'access.hasAccount': 'I have an account',
  'access.createFirm': 'Create a firm',
  'access.firmName': 'Firm name',
  'access.workspaceAddress': 'Workspace address',
  'access.yourName': 'Your name',
  'access.emailAddress': 'Email address',
  'access.password': 'Password',
  'access.confirmPassword': 'Confirm password',
  'access.passwordMismatch': 'Passwords do not match.',
  'access.onboardingFailed': 'We could not create your firm. Review the details and try again.',
  'access.pleaseWait': 'Please wait…',
  'access.createFirmAction': 'Create firm',
  'access.tenantSafe': 'Tenant-isolated and audit-ready by design',
  'access.signInFailed': 'We could not sign you in. Check your details and try again.',
  'access.signingIn': 'Signing in…',
  'access.signIn': 'Sign in',
  // Navigation and common controls
  'navigation.myWork': 'My work',
  'navigation.workflow': 'Workflow',
  'navigation.clients': 'Clients',
  'navigation.engagements': 'Engagements',
  'navigation.employees': 'Employees',
  'navigation.activityTrail': 'Activity trail',
  'common.language': 'Language',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.save': 'Save',
  'common.create': 'Create',
  'common.loading': 'Loading…',
  'common.error': 'Something went wrong.',
  'common.noDeadline': 'No deadline',
  'common.client': 'Client',
  'common.owner': 'Owner',
  'common.reviewer': 'Reviewer',
  'common.priority': 'Priority',
  'common.dueDate': 'Due date',
  'common.unassigned': 'Unassigned',
  // My Work and clients
  'myWork.eyebrow': 'Personal work queue',
  'myWork.title': 'My work',
  'myWork.description': 'Only work assigned to you in this firm is shown here.',
  'myWork.loadError': 'Your assigned work could not be loaded.',
  'myWork.loading': 'Loading your work…',
  'myWork.assignedWork': 'My assigned work',
  'myWork.noWorkItems': 'No work items.',
  'myWork.due': 'Due',
  'clients.eyebrow': 'Firm directory',
  'clients.title': 'Clients',
  'clients.description': 'Keep client identities and contact details ready for every engagement.',
  'clients.new': '+ New client',
  'clients.legalName': 'Legal name',
  'clients.displayName': 'Display name',
  'clients.primaryEmail': 'Primary email',
  'clients.save': 'Save client',
  'clients.createError': 'The client could not be created.',
  'clients.archiveError': 'The client could not be archived.',
  'clients.loadError': 'Clients could not be loaded.',
  'clients.loading': 'Loading clients…',
  'clients.emptyTitle': 'No clients yet',
  'clients.emptyDescription': 'Add the first client to begin organizing their work.',
  'clients.archive': 'Archive',
  'clients.active': 'active',
  'clients.archived': 'archived',
  // Workflow
  'workflow.filters': 'Filters',
  'workflow.dueState': 'Due state',
  'workflow.allDueStates': 'All due states',
  'workflow.overdue': 'Overdue',
  'workflow.dueToday': 'Due today',
  'workflow.dueSoon': 'Due soon',
  'workflow.noDueDate': 'No due date',
  'workflow.allPriorities': 'All priorities',
  'workflow.resetFilters': 'Reset filters',
  'workflow.clientWork': 'Client work',
  'workflow.description': 'Track every engagement from client request through review.',
  'workflow.loading': 'Loading workflow…',
  'workflow.loadError': 'The workflow could not be loaded.',
  'workflow.dragHelp': 'Drag a work item to another stage, or use its move left and move right buttons.',
  'workflow.assigned': 'Assigned:',
  'workflow.noWorkItemsInStage': 'No work items in this stage.',
  'workflow.openTaskWorkspace': 'Open task workspace',
  'workflow.loadingTask': 'Loading task…',
  'workflow.taskUnavailable': 'This task is not available in this workflow.',
  'workflow.workItem': 'Work item',
  'workflow.taskWorkspace': 'Task workspace',
  'workflow.backToWorkflow': 'Back to workflow',
  'workflow.taskDetails': 'Task details',
  'workflow.noDescription': 'No description provided.',
  'workflow.review': 'Review',
  'workflow.selectReviewer': 'Select reviewer',
  'workflow.noReviewer': 'No reviewer assigned.',
  'workflow.reviewerWarning': 'The owner is also the reviewer. This is allowed, but a separate reviewer is recommended.',
  'workflow.linkedDocumentRequests': 'Linked document requests',
  'workflow.noDocumentRequests': 'No document requests linked.',
  'workflow.recentActivity': 'Recent activity',
  'workflow.noActivity': 'No activity recorded for this work item.',
  'workflow.moveConflict': 'This work item was changed by another user. The board was refreshed; retry your move.',
  'workflow.moveError': 'The work item could not be moved.',
  'workflow.savedView': 'Saved view',
  'workflow.applySavedView': 'Apply saved workflow view',
  'workflow.availableDocumentRequests': 'Available document requests',
  'workflow.noMatchingDocumentRequests': 'No matching unlinked document requests.',
  'workflow.link': 'Link',
  'workflow.unlink': 'Unlink',
  'workflow.noWorkflow': 'No workflow yet',
  'workflow.createWorkflow': 'Create workflow',
  'workflow.loadingWorkflows': 'Loading workflows…',
  'workflow.loadWorkflowsError': 'Workflows could not be loaded. Please refresh and try again.',
  'workflow.onlyManagersCreate': 'Only firm owners, administrators, and managers can create workflows.',
  // Engagements
  'engagements.eyebrow': 'Recurring client work',
  'engagements.title': 'Engagements',
  'engagements.description': 'Launch repeatable client cycles and keep every prerequisite visible.',
  'engagements.createTemplate': 'Create template',
  'engagements.createEngagement': 'Start engagement',
  'engagements.createDocumentRequest': 'New document request',
  'engagements.templateError': 'The engagement template could not be created.',
  'engagements.createError': 'The engagement could not be started. It may already exist for that client and period.',
  'engagements.requestError': 'The document request could not be created.',
  'engagements.receiveError': 'The document request could not be marked received.',
  'engagements.loading': 'Loading engagements…',
  'engagements.loadError': 'Engagements could not be loaded.',
  // Employees
  'employees.eyebrow': 'Firm access',
  'employees.title': 'Employees',
  'employees.description': 'Create staff logins and make them available for work-item assignment.',
  'employees.denied': 'Only owners and administrators can manage employee access.',
  'employees.new': 'New employee',
  'employees.cancelNew': 'Cancel new employee',
  'employees.name': 'Employee name',
  'employees.email': 'Work email',
  'employees.temporaryPassword': 'Temporary password',
  'employees.role': 'Role',
  'employees.create': 'Create employee',
  'employees.createError': 'The employee could not be created. Review the details and try again.',
  'employees.loadError': 'Employees could not be loaded.',
  'employees.loading': 'Loading employees…',
  'employees.emptyTitle': 'No employees yet',
  'employees.emptyDescription': 'Create the first employee login for this firm.',
  // Audit and preview
  'audit.title': 'Activity trail',
  'audit.loading': 'Loading activity…',
  'audit.loadError': 'Activity could not be loaded.',
  'audit.empty': 'No activity found.',
  'audit.previous': 'Previous',
  'audit.next': 'Next',
  'preview.title': 'Preview access is not enabled',
  'preview.description': 'This firm is not part of the ForgeBoard Next.js preview. Use the existing ForgeBoard site to continue working.',
} as const

export type MessageKey = keyof typeof englishMessages

const germanMessages = {
  ...englishMessages,
  'access.introduction': 'ForgeBoard Einführung', 'access.eyebrow': 'Das Betriebssystem für Mandantenarbeit', 'access.title': 'Klarheit für jeden Mandantenauftrag.', 'access.description': 'ForgeBoard bietet Buchhaltungsteams einen ruhigen, verantwortlichen Ort für Fristen, Übergaben und wiederkehrende Arbeit.', 'access.oneView': 'Eine Übersicht', 'access.oneViewDetail': 'über jeden aktiven Auftrag', 'access.clearOwnership': 'Klare Verantwortung', 'access.clearOwnershipDetail': 'von der Vorbereitung bis zur Prüfung', 'access.auditReady': 'Prüfungsbereit', 'access.auditReadyDetail': 'mit jeder dokumentierten Änderung', 'access.secureFirmAccess': 'Sicherer Firmenzugang', 'access.welcomeBack': 'Willkommen zurück', 'access.buildWorkspace': 'Arbeitsbereich einrichten', 'access.signInDescription': 'Setzen Sie dort fort, wo Ihr Team aufgehört hat.', 'access.onboardingDescription': 'Erstellen Sie das erste Inhaberkonto für Ihre Firma.', 'access.accountAccess': 'Kontozugang', 'access.hasAccount': 'Ich habe ein Konto', 'access.createFirm': 'Firma erstellen', 'access.firmName': 'Firmenname', 'access.workspaceAddress': 'Arbeitsbereich-Adresse', 'access.yourName': 'Ihr Name', 'access.emailAddress': 'E-Mail-Adresse', 'access.password': 'Passwort', 'access.confirmPassword': 'Passwort bestätigen', 'access.passwordMismatch': 'Die Passwörter stimmen nicht überein.', 'access.onboardingFailed': 'Ihre Firma konnte nicht erstellt werden. Prüfen Sie die Angaben und versuchen Sie es erneut.', 'access.pleaseWait': 'Bitte warten…', 'access.createFirmAction': 'Firma erstellen', 'access.tenantSafe': 'Mandantengetrennt und revisionssicher entwickelt', 'access.signInFailed': 'Die Anmeldung war nicht möglich. Prüfen Sie Ihre Angaben und versuchen Sie es erneut.', 'access.signingIn': 'Anmeldung läuft…', 'access.signIn': 'Anmelden',
  'navigation.myWork': 'Meine Aufgaben', 'navigation.workflow': 'Arbeitsablauf', 'navigation.clients': 'Mandanten', 'navigation.engagements': 'Aufträge', 'navigation.employees': 'Mitarbeitende', 'navigation.activityTrail': 'Aktivitätsverlauf', 'common.language': 'Sprache', 'common.cancel': 'Abbrechen', 'common.close': 'Schließen', 'common.save': 'Speichern', 'common.create': 'Erstellen', 'common.loading': 'Wird geladen…', 'common.error': 'Etwas ist schiefgelaufen.', 'common.noDeadline': 'Keine Frist', 'common.client': 'Mandant', 'common.owner': 'Verantwortlich', 'common.reviewer': 'Prüfende Person', 'common.priority': 'Priorität', 'common.dueDate': 'Fälligkeitsdatum', 'common.unassigned': 'Nicht zugewiesen',
  'myWork.eyebrow': 'Persönliche Aufgabenliste', 'myWork.title': 'Meine Aufgaben', 'myWork.description': 'Hier wird nur Ihnen in dieser Firma zugewiesene Arbeit angezeigt.', 'myWork.loadError': 'Ihre zugewiesene Arbeit konnte nicht geladen werden.', 'myWork.loading': 'Ihre Aufgaben werden geladen…', 'myWork.assignedWork': 'Meine zugewiesene Arbeit', 'myWork.noWorkItems': 'Keine Aufgaben.', 'myWork.due': 'Fällig',
  'clients.eyebrow': 'Firmenverzeichnis', 'clients.title': 'Mandanten', 'clients.description': 'Halten Sie Mandantenidentitäten und Kontaktdaten für jeden Auftrag bereit.', 'clients.new': '+ Neuer Mandant', 'clients.legalName': 'Rechtlicher Name', 'clients.displayName': 'Anzeigename', 'clients.primaryEmail': 'Primäre E-Mail-Adresse', 'clients.save': 'Mandant speichern', 'clients.createError': 'Der Mandant konnte nicht erstellt werden.', 'clients.archiveError': 'Der Mandant konnte nicht archiviert werden.', 'clients.loadError': 'Mandanten konnten nicht geladen werden.', 'clients.loading': 'Mandanten werden geladen…', 'clients.emptyTitle': 'Noch keine Mandanten', 'clients.emptyDescription': 'Fügen Sie den ersten Mandanten hinzu, um seine Arbeit zu organisieren.', 'clients.archive': 'Archivieren', 'clients.active': 'aktiv', 'clients.archived': 'archiviert',
  'workflow.filters': 'Filter', 'workflow.dueState': 'Fälligkeitsstatus', 'workflow.allDueStates': 'Alle Fälligkeitsstatus', 'workflow.overdue': 'Überfällig', 'workflow.dueToday': 'Heute fällig', 'workflow.dueSoon': 'Bald fällig', 'workflow.noDueDate': 'Kein Fälligkeitsdatum', 'workflow.allPriorities': 'Alle Prioritäten', 'workflow.resetFilters': 'Filter zurücksetzen', 'workflow.clientWork': 'Mandantenarbeit', 'workflow.description': 'Verfolgen Sie jeden Auftrag von der Mandantenanfrage bis zur Prüfung.', 'workflow.loading': 'Arbeitsablauf wird geladen…', 'workflow.loadError': 'Der Arbeitsablauf konnte nicht geladen werden.', 'workflow.dragHelp': 'Ziehen Sie eine Aufgabe in eine andere Phase oder verwenden Sie die Schaltflächen zum Verschieben.', 'workflow.assigned': 'Zugewiesen:', 'workflow.noWorkItemsInStage': 'Keine Aufgaben in dieser Phase.', 'workflow.openTaskWorkspace': 'Aufgabenbereich öffnen', 'workflow.loadingTask': 'Aufgabe wird geladen…', 'workflow.taskUnavailable': 'Diese Aufgabe ist in diesem Arbeitsablauf nicht verfügbar.', 'workflow.workItem': 'Aufgabe', 'workflow.taskWorkspace': 'Aufgabenbereich', 'workflow.backToWorkflow': 'Zurück zum Arbeitsablauf', 'workflow.taskDetails': 'Aufgabendetails', 'workflow.noDescription': 'Keine Beschreibung vorhanden.', 'workflow.review': 'Prüfung', 'workflow.selectReviewer': 'Prüfende Person auswählen', 'workflow.noReviewer': 'Keine prüfende Person zugewiesen.', 'workflow.reviewerWarning': 'Die verantwortliche Person ist auch die prüfende Person. Dies ist erlaubt, eine getrennte Prüfung wird jedoch empfohlen.', 'workflow.linkedDocumentRequests': 'Verknüpfte Dokumentenanforderungen', 'workflow.noDocumentRequests': 'Keine Dokumentenanforderungen verknüpft.', 'workflow.recentActivity': 'Letzte Aktivitäten', 'workflow.noActivity': 'Für diese Aufgabe wurden keine Aktivitäten erfasst.', 'workflow.moveConflict': 'Diese Aufgabe wurde von einer anderen Person geändert. Das Board wurde aktualisiert; versuchen Sie die Verschiebung erneut.', 'workflow.moveError': 'Die Aufgabe konnte nicht verschoben werden.', 'workflow.savedView': 'Gespeicherte Ansicht', 'workflow.applySavedView': 'Gespeicherte Arbeitsablaufansicht anwenden', 'workflow.availableDocumentRequests': 'Verfügbare Dokumentenanforderungen', 'workflow.noMatchingDocumentRequests': 'Keine passenden nicht verknüpften Dokumentenanforderungen.', 'workflow.link': 'Verknüpfen', 'workflow.unlink': 'Verknüpfung lösen', 'workflow.noWorkflow': 'Noch kein Arbeitsablauf', 'workflow.createWorkflow': 'Arbeitsablauf erstellen', 'workflow.loadingWorkflows': 'Arbeitsabläufe werden geladen…', 'workflow.loadWorkflowsError': 'Arbeitsabläufe konnten nicht geladen werden. Aktualisieren Sie die Seite und versuchen Sie es erneut.', 'workflow.onlyManagersCreate': 'Nur Firmeninhaber, Administratoren und Manager können Arbeitsabläufe erstellen.',
  'engagements.eyebrow': 'Wiederkehrende Mandantenarbeit', 'engagements.title': 'Aufträge', 'engagements.description': 'Starten Sie wiederholbare Mandantenzyklen und behalten Sie alle Voraussetzungen im Blick.', 'engagements.createTemplate': 'Vorlage erstellen', 'engagements.createEngagement': 'Auftrag starten', 'engagements.createDocumentRequest': 'Neue Dokumentenanforderung', 'engagements.templateError': 'Die Auftragsvorlage konnte nicht erstellt werden.', 'engagements.createError': 'Der Auftrag konnte nicht gestartet werden. Möglicherweise existiert er bereits für diesen Mandanten und Zeitraum.', 'engagements.requestError': 'Die Dokumentenanforderung konnte nicht erstellt werden.', 'engagements.receiveError': 'Die Dokumentenanforderung konnte nicht als eingegangen markiert werden.', 'engagements.loading': 'Aufträge werden geladen…', 'engagements.loadError': 'Aufträge konnten nicht geladen werden.',
  'employees.eyebrow': 'Firmenzugang', 'employees.title': 'Mitarbeitende', 'employees.description': 'Erstellen Sie Mitarbeiterkonten und machen Sie sie für die Aufgabenzuweisung verfügbar.', 'employees.denied': 'Nur Inhaber und Administratoren können Mitarbeiterzugänge verwalten.', 'employees.new': 'Neue Mitarbeitende', 'employees.cancelNew': 'Neue Mitarbeitende abbrechen', 'employees.name': 'Name der mitarbeitenden Person', 'employees.email': 'Geschäftliche E-Mail-Adresse', 'employees.temporaryPassword': 'Temporäres Passwort', 'employees.role': 'Rolle', 'employees.create': 'Mitarbeitende erstellen', 'employees.createError': 'Die mitarbeitende Person konnte nicht erstellt werden. Prüfen Sie die Angaben und versuchen Sie es erneut.', 'employees.loadError': 'Mitarbeitende konnten nicht geladen werden.', 'employees.loading': 'Mitarbeitende werden geladen…', 'employees.emptyTitle': 'Noch keine Mitarbeitenden', 'employees.emptyDescription': 'Erstellen Sie den ersten Mitarbeiterzugang für diese Firma.',
  'audit.title': 'Aktivitätsverlauf', 'audit.loading': 'Aktivitäten werden geladen…', 'audit.loadError': 'Aktivitäten konnten nicht geladen werden.', 'audit.empty': 'Keine Aktivitäten gefunden.', 'audit.previous': 'Zurück', 'audit.next': 'Weiter', 'preview.title': 'Vorschauzugang ist nicht aktiviert', 'preview.description': 'Diese Firma ist nicht Teil der ForgeBoard-Next.js-Vorschau. Verwenden Sie die bestehende ForgeBoard-Seite, um weiterzuarbeiten.',
} as const satisfies Record<MessageKey, string>

export const messages = {
  en: englishMessages,
  de: germanMessages,
} as const satisfies Record<Language, Record<MessageKey, string>>

export function readLanguage(value?: string): Language {
  return value === 'de' ? 'de' : 'en'
}

export function languageCookie(language: Language): string {
  return `${LANGUAGE_COOKIE}=${language}; Path=/; SameSite=Lax${process.env.NODE_ENV === 'production' ? '; Secure' : ''}`
}
