'use client'

import type { FirmContext } from '@/lib/firm-context'
import { firmTag, forgeboardApi } from '@/store/api'

export interface WorkflowBoard { id: string; name: string; workflowSlug: string; stages: WorkflowStage[] }
export interface PublicWorkflowRequest { firm: FirmContext; workflowSlug: string }
export interface WorkflowRequest { firm: FirmContext; workflowId: string }
export type WorkPriority = 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT'
export type StageAttention = 'NONE' | 'BLOCKED' | 'AWAITING_REVIEW'
export interface WorkItem { id: string; taskReference: string; clientId: string; stageId: string; title: string; description: string; dueDate: string | null; priority: WorkPriority; rank: number; version: number; ownerUserId: string | null; ownerDisplayName: string | null; reviewerUserId: string | null; reviewerDisplayName: string | null }
export interface WorkflowStage { id: string; name: string; attention: StageAttention; position: number; items: WorkItem[] }
export interface DocumentRequestSummary { id: string; label: string; dueDate: string | null; status: 'REQUESTED' | 'RECEIVED'; receivedAt: string | null }
export interface ActivitySummary { action: string; occurredAt: string; summary: Record<string, unknown>; actorType: string; source: string; targetId: string }
export interface WorkItemDetail { item: WorkItem; clientDisplayName: string; documentRequests: DocumentRequestSummary[]; activity: ActivitySummary[] }
export interface WorkflowSummary { id: string; name: string; workflowSlug: string }
export interface CreateWorkflowDetails { name: string; stages: Array<{ name: string; attention: StageAttention }> }
export interface WorkflowFilterView { id: string; name: string; clientId: string | null; ownerUserId: string | null; dueState: 'OVERDUE' | 'DUE_TODAY' | 'DUE_SOON' | 'NO_DUE_DATE' | null; priority: WorkPriority | null; unassigned: boolean | null }
export interface CreateWorkItemDetails { clientId: string; stageId: string; title: string; description: string; dueDate: string | null; priority: WorkPriority }

export const workflowApi = forgeboardApi.injectEndpoints({ endpoints: (build) => ({
  getWorkflowBoard: build.query<WorkflowBoard, PublicWorkflowRequest>({ query: ({ workflowSlug }) => ({ url: `workflows/public/${encodeURIComponent(workflowSlug)}` }), providesTags: (result, _error, { firm, workflowSlug }) => [{ type: 'Workflow', id: firmTag(firm.firmId, result?.id ?? workflowSlug) }] }),
  updateWorkflow: build.mutation<WorkflowBoard, WorkflowRequest & { body: Record<string, unknown> }>({ query: ({ workflowId, body }) => ({ url: `workflows/${encodeURIComponent(workflowId)}`, method: 'PUT', body }), invalidatesTags: (_result, _error, { firm, workflowId }) => [{ type: 'Workflow', id: firmTag(firm.firmId, workflowId) }] }),
  getWorkItemDetail: build.query<WorkItemDetail, PublicWorkflowRequest & { taskReference: string }>({ query: ({ workflowSlug, taskReference }) => ({ url: `workflows/public/${encodeURIComponent(workflowSlug)}/items/${encodeURIComponent(taskReference)}` }), providesTags: (result, _error, { firm, workflowSlug, taskReference }) => [{ type: 'WorkItem', id: firmTag(firm.firmId) }, { type: 'WorkItem', id: firmTag(firm.firmId, result?.item?.id ?? taskReference) }, { type: 'Workflow', id: firmTag(firm.firmId, workflowSlug) }] }),
  moveWorkItem: build.mutation<WorkItem, WorkflowRequest & { itemId: string; targetStageId: string; expectedVersion: number }>({ query: ({ workflowId, itemId, targetStageId, expectedVersion }) => ({ url: `workflows/${encodeURIComponent(workflowId)}/items/${encodeURIComponent(itemId)}/position`, method: 'PATCH', body: { targetStageId, beforeItemId: null, afterItemId: null, expectedVersion } }), invalidatesTags: (_result, _error, { firm, workflowId, itemId }) => [{ type: 'Workflow', id: firmTag(firm.firmId, workflowId) }, { type: 'WorkItem', id: firmTag(firm.firmId, itemId) }, { type: 'MyWork', id: firmTag(firm.firmId) }] }),
  createWorkItem: build.mutation<WorkItem, WorkflowRequest & { details: CreateWorkItemDetails }>({ query: ({ workflowId, details }) => ({ url: `workflows/${encodeURIComponent(workflowId)}/items`, method: 'POST', body: details }), invalidatesTags: (_result, _error, { firm, workflowId }) => [{ type: 'Workflow', id: firmTag(firm.firmId, workflowId) }, { type: 'MyWork', id: firmTag(firm.firmId) }] }),
  updateWorkItemOwner: build.mutation<WorkItem, WorkflowRequest & { itemId: string; ownerUserId: string | null }>({ query: ({ workflowId, itemId, ownerUserId }) => ({ url: `workflows/${encodeURIComponent(workflowId)}/items/${encodeURIComponent(itemId)}/owner`, method: 'PUT', body: { ownerUserId } }), invalidatesTags: (_result, _error, { firm, workflowId, itemId }) => [{ type: 'Workflow', id: firmTag(firm.firmId, workflowId) }, { type: 'WorkItem', id: firmTag(firm.firmId, itemId) }, { type: 'MyWork', id: firmTag(firm.firmId) }] }),
  updateWorkItemReviewer: build.mutation<WorkItem, WorkflowRequest & { itemId: string; userId: string | null }>({ query: ({ workflowId, itemId, userId }) => ({ url: `workflows/${encodeURIComponent(workflowId)}/items/${encodeURIComponent(itemId)}/reviewer`, method: 'PUT', body: { userId } }), invalidatesTags: (_result, _error, { firm, workflowId, itemId }) => [{ type: 'Workflow', id: firmTag(firm.firmId, workflowId) }, { type: 'WorkItem', id: firmTag(firm.firmId, itemId) }] }),
  linkDocumentRequest: build.mutation<WorkItemDetail, WorkflowRequest & { itemId: string; requestId: string }>({ query: ({ workflowId, itemId, requestId }) => ({ url: `workflows/${encodeURIComponent(workflowId)}/items/${encodeURIComponent(itemId)}/document-requests/${encodeURIComponent(requestId)}`, method: 'PUT' }), invalidatesTags: (_result, _error, { firm, workflowId, itemId }) => [{ type: 'WorkItem', id: firmTag(firm.firmId, itemId) }, { type: 'Workflow', id: firmTag(firm.firmId, workflowId) }] }),
  unlinkDocumentRequest: build.mutation<WorkItemDetail, WorkflowRequest & { itemId: string; requestId: string }>({ query: ({ workflowId, itemId, requestId }) => ({ url: `workflows/${encodeURIComponent(workflowId)}/items/${encodeURIComponent(itemId)}/document-requests/${encodeURIComponent(requestId)}`, method: 'DELETE' }), invalidatesTags: (_result, _error, { firm, workflowId, itemId }) => [{ type: 'WorkItem', id: firmTag(firm.firmId, itemId) }, { type: 'Workflow', id: firmTag(firm.firmId, workflowId) }] }),
  getWorkflowViews: build.query<WorkflowFilterView[], { firm: FirmContext }>({ query: () => ({ url: 'workflows/views' }), providesTags: (_result, _error, { firm }) => [{ type: 'WorkflowView', id: firmTag(firm.firmId) }] }),
  createWorkflowView: build.mutation<WorkflowFilterView, { firm: FirmContext; view: Omit<WorkflowFilterView, 'id'> }>({ query: ({ view }) => ({ url: 'workflows/views', method: 'POST', body: view }), invalidatesTags: (_result, _error, { firm }) => [{ type: 'WorkflowView', id: firmTag(firm.firmId) }] }),
  deleteWorkflowView: build.mutation<void, { firm: FirmContext; viewId: string }>({ query: ({ viewId }) => ({ url: `workflows/views/${encodeURIComponent(viewId)}`, method: 'DELETE' }), invalidatesTags: (_result, _error, { firm }) => [{ type: 'WorkflowView', id: firmTag(firm.firmId) }] }),
  getWorkflows: build.query<WorkflowSummary[], { firm: FirmContext }>({ query: () => ({ url: 'workflows' }), providesTags: (_result, _error, { firm }) => [{ type: 'Workflow', id: firmTag(firm.firmId) }] }),
  createWorkflow: build.mutation<WorkflowBoard, { firm: FirmContext; details: CreateWorkflowDetails }>({ query: ({ details }) => ({ url: 'workflows', method: 'POST', body: details }), invalidatesTags: (_result, _error, { firm }) => [{ type: 'Workflow', id: firmTag(firm.firmId) }] }),
}) })
export const { useCreateWorkflowMutation, useCreateWorkflowViewMutation, useCreateWorkItemMutation, useDeleteWorkflowViewMutation, useGetWorkflowBoardQuery, useGetWorkflowViewsQuery, useGetWorkflowsQuery, useGetWorkItemDetailQuery, useLinkDocumentRequestMutation, useMoveWorkItemMutation, useUnlinkDocumentRequestMutation, useUpdateWorkflowMutation, useUpdateWorkItemOwnerMutation, useUpdateWorkItemReviewerMutation } = workflowApi
export const { createWorkItem, getWorkflowBoard, moveWorkItem } = workflowApi.endpoints
export { useGetDocumentRequestsQuery } from '@/features/engagements/engagements-transport'
export type { DocumentRequest } from '@/features/engagements/engagements-transport'
