import { FormEvent, useEffect, useState } from 'react'
import { archiveClient, Client, createClient, listClients } from './api/clients'
import { createFirm, currentSession, listAccessibleFirms, login, logout, SessionIdentity } from './api/session'
import { WorkflowView } from './WorkflowView'

const FIRM_KEY = 'forgeboard.selectedFirmId'
function Clients({ firmId }: { firmId: string }) {
  const [clients, setClients] = useState<Client[]>([]); const [error, setError] = useState(''); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(true)
  useEffect(() => { listClients(firmId).then(setClients).catch(() => setError('Clients could not be loaded.')).finally(() => setLoading(false)) }, [firmId])
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setError(''); try { const created = await createClient(firmId, { legalName: String(data.get('legalName')), displayName: String(data.get('displayName')), primaryEmail: String(data.get('primaryEmail')) }); setClients((all) => [...all, created]); form.reset(); setCreating(false) } catch { setError('The client could not be created.') } }
  async function archive(client: Client) { try { const archived = await archiveClient(firmId, client.id); setClients((all) => all.map((item) => item.id === archived.id ? archived : item)) } catch { setError('The client could not be archived.') } }
  return <section className="workspace clients-view"><header><div><p className="eyebrow">Firm directory</p><h1>Clients</h1><p>Keep client identities and contact details ready for every engagement.</p></div><button type="button" onClick={() => setCreating(!creating)}>{creating ? 'Cancel' : '+ New client'}</button></header>
    {creating && <form className="client-form" onSubmit={submit}><label>Legal name<input name="legalName" required maxLength={200} /></label><label>Display name<input name="displayName" required maxLength={160} /></label><label>Primary email<input name="primaryEmail" type="email" maxLength={320} /></label><button className="primary-action">Save client</button></form>}{error && <p className="form-error" role="alert">{error}</p>}
    {loading ? <p className="empty-state">Loading clients…</p> : clients.length === 0 ? <div className="empty-state"><h2>No clients yet</h2><p>Add the first client to begin organizing their work.</p></div> : <div className="client-list" aria-label="Clients">{clients.map((client) => <article className={`client-row ${client.status === 'ARCHIVED' ? 'archived' : ''}`} key={client.id}><div><h2>{client.displayName}</h2><p>{client.legalName}{client.primaryEmail ? ` · ${client.primaryEmail}` : ''}</p></div><span className="status">{client.status.toLowerCase()}</span>{client.status === 'ACTIVE' && <button className="secondary" onClick={() => archive(client)}>Archive</button>}</article>)}</div>}
  </section>
}

function Shell({ identity, firmName, firmId, onLogout }: { identity: SessionIdentity; firmName: string; firmId: string | null; onLogout: () => void }) {
  const [view, setView] = useState<'workflow' | 'clients'>('workflow')
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span>F</span> ForgeBoard</div><nav aria-label="Primary navigation"><button className={view === 'workflow' ? 'active' : ''} onClick={() => setView('workflow')}>Workflow</button><button className={view === 'clients' ? 'active' : ''} onClick={() => setView('clients')}>Clients</button><button disabled>Engagements</button><button disabled>Reports</button></nav><div className="firm-card"><small>Current firm</small><strong>{firmName}</strong><span>{identity.email}</span><button className="sidebar-action" onClick={onLogout}>Sign out</button></div></aside>{firmId ? view === 'workflow' ? <WorkflowView firmId={firmId} /> : <Clients firmId={firmId} /> : <section className="workspace"><div className="empty-state"><h1>Select a firm</h1><p>Create a firm in this browser before managing work.</p></div></section>}</main>
}

function Access({ onAuthenticated }: { onAuthenticated: (identity: SessionIdentity, firmName?: string, firmId?: string) => Promise<void> }) {
  const [mode, setMode] = useState<'login' | 'onboarding'>('login'); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); const email = String(data.get('email')); const password = String(data.get('password')); try { let firmName: string | undefined; let firmId: string | undefined; if (mode === 'onboarding') { firmName = String(data.get('firmName')); const result = await createFirm({ firmName, firmSlug: String(data.get('firmSlug')), ownerName: String(data.get('ownerName')), ownerEmail: email, password }); firmId = result.firmId } await onAuthenticated(await login(email, password), firmName, firmId) } catch { setError(mode === 'login' ? 'We could not sign you in. Check your details and try again.' : 'We could not create your firm. Review the details and try again.') } finally { setBusy(false) } }
  return <main className="access-shell"><section className="access-intro"><div className="brand"><span>F</span> ForgeBoard</div><p className="eyebrow">Built for accounting teams</p><h1>Client work, clearly moving forward.</h1><p>Keep deadlines, handoffs, and missing documents visible in one shared workflow.</p><ul><li>Know what needs attention today</li><li>Make every handoff auditable</li><li>Give your team and AI agents one source of truth</li></ul></section><section className="access-panel" aria-labelledby="access-title"><div className="mode-switch" aria-label="Account access"><button type="button" aria-pressed={mode === 'login'} onClick={() => setMode('login')}>I have an account</button><button type="button" aria-pressed={mode === 'onboarding'} onClick={() => setMode('onboarding')}>Create a firm</button></div><h2 id="access-title">{mode === 'login' ? 'Welcome back' : 'Set up your workspace'}</h2><p>{mode === 'login' ? 'Sign in to continue to your firm.' : 'Create the first owner account for your firm.'}</p><form onSubmit={submit}>{mode === 'onboarding' && <><label>Firm name<input name="firmName" autoComplete="organization" required maxLength={160} /></label><label>Workspace address<div className="slug-field"><span>forgeboard.app/</span><input name="firmSlug" aria-label="Workspace address" required maxLength={80} pattern="[a-z0-9-]+" placeholder="hearth-accounting" /></div></label><label>Your name<input name="ownerName" autoComplete="name" required maxLength={160} /></label></>}<label>Email address<input name="email" type="email" autoComplete="email" required /></label><label>Password<input name="password" type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} required minLength={12} /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-action" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create firm'}</button></form></section></main>
}

export function App() {
  const [identity, setIdentity] = useState<SessionIdentity | null>(null); const [checking, setChecking] = useState(true); const [firmName, setFirmName] = useState('Your firm'); const [firmId, setFirmId] = useState<string | null>(() => localStorage.getItem(FIRM_KEY))
  useEffect(() => { currentSession().then(setIdentity).catch(() => undefined).finally(() => setChecking(false)) }, [])
  if (checking) return <main className="loading-shell" aria-live="polite">Opening ForgeBoard…</main>
  if (!identity) return <Access onAuthenticated={async (next, firm, selected) => { let resolvedId = selected; let resolvedName = firm; if (!resolvedId) { const accessible = await listAccessibleFirms(); resolvedId = accessible[0]?.id; resolvedName = accessible[0]?.name } setIdentity(next); if (resolvedName) setFirmName(resolvedName); if (resolvedId) { localStorage.setItem(FIRM_KEY, resolvedId); setFirmId(resolvedId) } }} />
  return <Shell identity={identity} firmName={firmName} firmId={firmId} onLogout={async () => { await logout(); setIdentity(null) }} />
}
