'use client'

import type { FirmContext } from '@/lib/firm-context'
import { firmTag, forgeboardApi, portfolioInvalidation } from '@/store/api'

export type Recurrence = 'MONTHLY' | 'QUARTERLY' | 'ANNUAL'
export interface TemplateChecklistItem { label: string; required: boolean; position: number }
export interface EngagementTemplate { id: string; name: string; workflowId: string; recurrence: Recurrence; defaultWorkItemTitle: string; dueDay: number; checklistItems: TemplateChecklistItem[]; version: number; currentVersion: number; enrolledClientCount: number }
export type EngagementTemplateInput = Pick<EngagementTemplate, 'name' | 'workflowId' | 'recurrence' | 'defaultWorkItemTitle' | 'dueDay'> & { checklistItems: Array<Pick<TemplateChecklistItem, 'label' | 'required'>> }
export interface TemplateEnrollmentClient { id: string; legalName: string; displayName: string; primaryEmail: string | null; version: number }
export type EngagementStatus = 'ACTIVE' | 'BLOCKED' | 'AWAITING_REVIEW' | 'COMPLETE' | 'CANCELLED' | 'ARCHIVED'
export interface Engagement { id: string; templateId: string; clientId: string; workflowId: string; workItemId: string | null; periodStart: string; periodEnd: string; dueDate: string; status: EngagementStatus; statusChangedAt: string; version: number }
export interface EngagementChecklistItem { id: string; label: string; required: boolean; position: number; completed: boolean; completedAt: string | null; completedBy: string | null; canUpdate: boolean; version: number }
export interface ReviewDecision { id: string; actorId: string; decision: 'APPROVED' | 'RETURNED'; note: string | null; occurredAt: string }
export interface EngagementDetail { engagement: Engagement; history: { reviewDecisions: ReviewDecision[] } }
export interface DocumentRequest { id: string; clientId: string; label: string; externalReference: string | null; dueDate: string | null; status: 'REQUESTED' | 'RECEIVED'; receivedAt: string | null; followUpState: 'OPEN' | 'REMINDER_RECORDED' | 'ESCALATED' | 'RECEIVED'; remindedAt: string | null; escalatedAt: string | null; version: number }
export interface RecurrenceFailure { id: string; templateId: string; templateName: string; periodStart: string; failedDefinitionVersion: number; currentDefinitionVersion: number; failureDetail: string; automaticRetryAttempted: boolean; generateNowDisabled: boolean }

export const engagementsApi = forgeboardApi.injectEndpoints({ endpoints: (build) => ({
  getEngagementTemplates: build.query<EngagementTemplate[], { firm: FirmContext }>({ query: () => ({ url: 'engagements/templates' }), providesTags: (result, _error, { firm }) => [{ type: 'EngagementTemplate', id: firmTag(firm.firmId) }, ...(result ?? []).map((template) => ({ type: 'EngagementTemplate' as const, id: firmTag(firm.firmId, template.id) }))] }),
  getRecurrenceFailures: build.query<RecurrenceFailure[], { firm: FirmContext }>({ query: () => ({ url: 'engagements/recurrence-failures' }), providesTags: (_result, _error, { firm }) => [{ type: 'EngagementTemplate', id: firmTag(firm.firmId, 'recurrence-failures') }] }),
  retryRecurrenceFailure: build.mutation<RecurrenceFailure, { firm: FirmContext; runId: string }>({ query: ({ runId }) => ({ url: `engagements/recurrence-failures/${encodeURIComponent(runId)}/retry`, method: 'POST' }), invalidatesTags: (_result, _error, { firm }) => [...portfolioInvalidation(_error, firm.firmId), { type: 'EngagementTemplate', id: firmTag(firm.firmId, 'recurrence-failures') }, { type: 'Engagement', id: firmTag(firm.firmId) }] }),
  markRecurrenceFailureSolved: build.mutation<void, { firm: FirmContext; runId: string }>({ query: ({ runId }) => ({ url: `engagements/recurrence-failures/${encodeURIComponent(runId)}/mark-solved`, method: 'POST' }), invalidatesTags: (_result, _error, { firm }) => [{ type: 'EngagementTemplate', id: firmTag(firm.firmId, 'recurrence-failures') }] }),
  generateRecurrenceFailure: build.mutation<RecurrenceFailure, { firm: FirmContext; runId: string }>({ query: ({ runId }) => ({ url: `engagements/recurrence-failures/${encodeURIComponent(runId)}/generate`, method: 'POST' }), invalidatesTags: (_result, _error, { firm }) => [...portfolioInvalidation(_error, firm.firmId), { type: 'EngagementTemplate', id: firmTag(firm.firmId, 'recurrence-failures') }, { type: 'Engagement', id: firmTag(firm.firmId) }] }),
  createEngagementTemplate: build.mutation<EngagementTemplate, { firm: FirmContext; template: EngagementTemplateInput }>({ query: ({ template }) => ({ url: 'engagements/templates', method: 'POST', body: template }), invalidatesTags: (_result, _error, { firm }) => [{ type: 'EngagementTemplate', id: firmTag(firm.firmId) }] }),
  updateEngagementTemplate: build.mutation<EngagementTemplate, { firm: FirmContext; templateId: string; template: EngagementTemplateInput; expectedVersion: number }>({ query: ({ templateId, template, expectedVersion }) => ({ url: `engagements/templates/${encodeURIComponent(templateId)}`, method: 'PUT', body: { ...template, expectedVersion } }), invalidatesTags: (_result, _error, { firm, templateId }) => [...portfolioInvalidation(_error, firm.firmId), { type: 'EngagementTemplate', id: firmTag(firm.firmId) }, { type: 'EngagementTemplate', id: firmTag(firm.firmId, templateId) }] }),
  getTemplateEnrollments: build.query<TemplateEnrollmentClient[], { firm: FirmContext; templateId: string }>({ query: ({ templateId }) => ({ url: `engagements/templates/${encodeURIComponent(templateId)}/enrollments` }), providesTags: (_result, _error, { firm, templateId }) => [{ type: 'EngagementTemplate', id: firmTag(firm.firmId, templateId) }] }),
  enrollTemplateClients: build.mutation<{ enrolledClientCount: number }, { firm: FirmContext; templateId: string; clientIds: string[] }>({ query: ({ templateId, clientIds }) => ({ url: `engagements/templates/${encodeURIComponent(templateId)}/enrollments`, method: 'POST', body: { clientIds } }), invalidatesTags: (_result, _error, { firm, templateId }) => [{ type: 'EngagementTemplate', id: firmTag(firm.firmId) }, { type: 'EngagementTemplate', id: firmTag(firm.firmId, templateId) }] }),
  unenrollTemplateClients: build.mutation<{ enrolledClientCount: number }, { firm: FirmContext; templateId: string; clientIds: string[] }>({ query: ({ templateId, clientIds }) => ({ url: `engagements/templates/${encodeURIComponent(templateId)}/enrollments`, method: 'DELETE', body: { clientIds } }), invalidatesTags: (_result, _error, { firm, templateId }) => [{ type: 'EngagementTemplate', id: firmTag(firm.firmId) }, { type: 'EngagementTemplate', id: firmTag(firm.firmId, templateId) }] }),
  getEngagements: build.query<Engagement[], { firm: FirmContext }>({ query: () => ({ url: 'engagements' }), providesTags: (_result, _error, { firm }) => [{ type: 'Engagement', id: firmTag(firm.firmId) }] }),
  getEngagement: build.query<EngagementDetail, { firm: FirmContext; engagementId: string }>({ query: ({ engagementId }) => ({ url: `engagements/${encodeURIComponent(engagementId)}` }), providesTags: (_result, _error, { firm, engagementId }) => [{ type: 'Engagement', id: firmTag(firm.firmId) }, { type: 'Engagement', id: firmTag(firm.firmId, engagementId) }] }),
  getEngagementChecklist: build.query<EngagementChecklistItem[], { firm: FirmContext; engagementId: string }>({ query: ({ engagementId }) => ({ url: `engagements/${encodeURIComponent(engagementId)}/checklist` }), providesTags: (_result, _error, { firm, engagementId }) => [{ type: 'EngagementChecklist', id: firmTag(firm.firmId, engagementId) }] }),
  toggleEngagementChecklistItem: build.mutation<EngagementChecklistItem, { firm: FirmContext; engagementId: string; checklistItemId: string; completed: boolean; expectedVersion: number }>({ query: ({ engagementId, checklistItemId, completed, expectedVersion }) => ({ url: `engagements/${encodeURIComponent(engagementId)}/checklist/${encodeURIComponent(checklistItemId)}`, method: 'PATCH', body: { completed, expectedVersion } }), invalidatesTags: (_result, _error, { firm, engagementId }) => [{ type: 'EngagementChecklist', id: firmTag(firm.firmId, engagementId) }, { type: 'Engagement', id: firmTag(firm.firmId, engagementId) }] }),
  changeEngagementLifecycle: build.mutation<Engagement, { firm: FirmContext; engagementId: string; action: 'cancel' | 'reopen' | 'archive' | 'unarchive'; expectedVersion: number; workflowId: string; workItemId: string | null }>({ query: ({ engagementId, action, expectedVersion }) => ({ url: `engagements/${encodeURIComponent(engagementId)}/${action}`, method: 'POST', body: { expectedVersion } }), invalidatesTags: (_result, _error, { firm, engagementId, workflowId, workItemId }) => [...portfolioInvalidation(_error, firm.firmId), { type: 'Engagement', id: firmTag(firm.firmId) }, { type: 'Engagement', id: firmTag(firm.firmId, engagementId) }, { type: 'Workflow', id: firmTag(firm.firmId, workflowId) }, { type: 'WorkItem', id: firmTag(firm.firmId) }, ...(workItemId ? [{ type: 'WorkItem' as const, id: firmTag(firm.firmId, workItemId) }] : []), { type: 'MyWork', id: firmTag(firm.firmId) }] }),
  createEngagement: build.mutation<Engagement, { firm: FirmContext; templateId: string; details: { clientId: string; periodStart: string } }>({ query: ({ templateId, details }) => ({ url: `engagements/templates/${encodeURIComponent(templateId)}/instances`, method: 'POST', body: details }), invalidatesTags: (result, _error, { firm }) => [...portfolioInvalidation(_error, firm.firmId), { type: 'Engagement', id: firmTag(firm.firmId) }, { type: 'MyWork', id: firmTag(firm.firmId) }, ...(result ? [{ type: 'Workflow' as const, id: firmTag(firm.firmId, result.workflowId) }] : [])] }),
  getDocumentRequests: build.query<DocumentRequest[], { firm: FirmContext }>({ query: () => ({ url: 'document-requests' }), providesTags: (_result, _error, { firm }) => [{ type: 'DocumentRequest', id: firmTag(firm.firmId) }] }),
  createDocumentRequest: build.mutation<DocumentRequest, { firm: FirmContext; request: Omit<DocumentRequest, 'id' | 'status' | 'receivedAt' | 'followUpState' | 'remindedAt' | 'escalatedAt' | 'version'> }>({ query: ({ request }) => ({ url: 'document-requests', method: 'POST', body: request }), invalidatesTags: (_result, _error, { firm }) => [{ type: 'DocumentRequest', id: firmTag(firm.firmId) }] }),
  receiveDocumentRequest: build.mutation<DocumentRequest, { firm: FirmContext; requestId: string }>({ query: ({ requestId }) => ({ url: `document-requests/${encodeURIComponent(requestId)}/received`, method: 'PATCH' }), invalidatesTags: (_result, _error, { firm }) => [{ type: 'DocumentRequest', id: firmTag(firm.firmId) }, { type: 'WorkItem', id: firmTag(firm.firmId) }] }),
  recordDocumentRequestReminder: build.mutation<DocumentRequest, { firm: FirmContext; requestId: string }>({ query: ({ requestId }) => ({ url: `document-requests/${encodeURIComponent(requestId)}/reminded`, method: 'PATCH' }), invalidatesTags: (_result, _error, { firm }) => [{ type: 'DocumentRequest', id: firmTag(firm.firmId) }, { type: 'WorkItem', id: firmTag(firm.firmId) }] }),
  escalateDocumentRequest: build.mutation<DocumentRequest, { firm: FirmContext; requestId: string }>({ query: ({ requestId }) => ({ url: `document-requests/${encodeURIComponent(requestId)}/escalated`, method: 'PATCH' }), invalidatesTags: (_result, _error, { firm }) => [{ type: 'DocumentRequest', id: firmTag(firm.firmId) }, { type: 'WorkItem', id: firmTag(firm.firmId) }] }),
}) })
export const { useChangeEngagementLifecycleMutation, useCreateDocumentRequestMutation, useCreateEngagementMutation, useCreateEngagementTemplateMutation, useEnrollTemplateClientsMutation, useEscalateDocumentRequestMutation, useGenerateRecurrenceFailureMutation, useGetDocumentRequestsQuery, useGetEngagementChecklistQuery, useGetEngagementQuery, useGetEngagementsQuery, useGetEngagementTemplatesQuery, useGetRecurrenceFailuresQuery, useGetTemplateEnrollmentsQuery, useMarkRecurrenceFailureSolvedMutation, useReceiveDocumentRequestMutation, useRecordDocumentRequestReminderMutation, useRetryRecurrenceFailureMutation, useToggleEngagementChecklistItemMutation, useUnenrollTemplateClientsMutation, useUpdateEngagementTemplateMutation } = engagementsApi
