// @vitest-environment jsdom
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { engagementsApi } from './engagements-transport'
import { workflowApi } from '@/features/workflow/workflow-transport'
import { makeStore } from '@/store/store'
const firmA = { firmId: 'firm-a', firmSlug: 'hearth', role: 'OWNER' as const }; const firmB = { firmId: 'firm-b', firmSlug: 'northstar', role: 'OWNER' as const }
describe('engagements transport', () => { beforeEach(() => vi.stubGlobal('fetch', vi.fn(async (input: RequestInfo | URL) => { const url = (input as Request).url; return new Response(JSON.stringify(url.includes('/instances') ? { id: 'engagement-1', workflowId: 'workflow-1' } : url.includes('workflows/public/') && !url.includes('/items/') ? { id: 'workflow-1', stages: [] } : []), { headers: { 'Content-Type': 'application/json' } }) })))
  it('refreshes only the generated engagement workflow board', async () => { const store = makeStore(); await Promise.all([store.dispatch(workflowApi.endpoints.getWorkflowBoard.initiate({ firm: firmA, workflowSlug: 'monthly-close' })), store.dispatch(workflowApi.endpoints.getWorkflowBoard.initiate({ firm: firmB, workflowSlug: 'monthly-close' }))]); await store.dispatch(engagementsApi.endpoints.createEngagement.initiate({ firm: firmA, templateId: 'template-1', details: { clientId: 'client-1', periodStart: '2026-07-01' } })); await new Promise((resolve) => setTimeout(resolve, 0)); const requests = vi.mocked(fetch).mock.calls.map(([input]) => input as Request).filter((request) => request.url.includes('workflows/public/monthly-close')); expect(requests).toHaveLength(3) })
  it('refreshes linked task details only in the firm receiving a document request', async () => { const store = makeStore(); await Promise.all([store.dispatch(workflowApi.endpoints.getWorkItemDetail.initiate({ firm: firmA, workflowSlug: 'monthly-close', taskReference: 'FB-1042' })), store.dispatch(workflowApi.endpoints.getWorkItemDetail.initiate({ firm: firmB, workflowSlug: 'monthly-close', taskReference: 'FB-1042' }))]); await store.dispatch(engagementsApi.endpoints.receiveDocumentRequest.initiate({ firm: firmA, requestId: 'request-1' })); await new Promise((resolve) => setTimeout(resolve, 0)); const requests = vi.mocked(fetch).mock.calls.map(([input]) => input as Request).filter((request) => request.url.includes('workflows/public/monthly-close/items/FB-1042')); expect(requests).toHaveLength(3) }) })
